services:
  - type: web
    name: demandai-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGO_URI
        sync: false
      - key: ML_SERVICE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: ALERT_EMAIL
        sync: false

  - type: web
    name: demandai-ml
    runtime: docker
    rootDir: ml-service
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 5001
      - key: MONGO_URI
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
